[package]
name = "encrypted_backup-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[lib]
path = "src/lib.rs"

[build-dependencies]
cc = "1"
cxx-build = "1"

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }
cxx = "1"

[dependencies.bip138]
path = ".."

[[bin]]
name = "decode"
path = "fuzz_targets/decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "encode"
path = "fuzz_targets/encode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_deriv_paths"
path = "fuzz_targets/parse_deriv_paths.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_individual_secrets"
path = "fuzz_targets/parse_individual_secrets.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_encrypted_payload"
path = "fuzz_targets/parse_encrypted_payload.rs"
test = false
doc = false
bench = false

[[bin]]
name = "diff_decode"
path = "fuzz_targets/diff_decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "diff_decrypt"
path = "fuzz_targets/diff_decrypt.rs"
test = false
doc = false
bench = false

[[bin]]
name = "diff_encode"
path = "fuzz_targets/diff_encode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "diff_plaintext"
path = "fuzz_targets/diff_plaintext.rs"
test = false
doc = false
bench = false
